Add the `Interface` option to `Pinger`
prometheus-community/pro-bing pull request #123
Opened 2024-10-29 12:03 UTC by MatthieuCoder

This is a rebase of #32 to match the current HEAD or main.

This allows using `pro-bing` to use VRFs interfaces and IPv6 link-local addresses.

2024-10-29 12:08 UTC, SuperQ commented on ping.go
> +	Interface string
I think we wanted to have this be something `InterfaceDevice` to avoid conflict with the `interface` keyword.

2024-10-29 12:12 UTC, MatthieuCoder commented on ping.go
> +	Interface string
I changed it to `InterfaceDevice`, but wouldn't `InterfaceName` be more appropriate ?

2024-10-29 12:17 UTC, SuperQ commented on ping.go
> +	Interface string
I don't have a strong opinion here. `InterfaceName` also works for me. Up to you.

2024-10-29 12:17 UTC, SuperQ commented
It seems like the test fails on permissions.

2024-10-29 12:35 UTC, MatthieuCoder commented
As @ilolicon pointed out, the tests run just fine on a local hosts & using the circleci local cli:

```
matthieu@matthieu-archlinux ~/pro-bing (main)> circleci local execute build
Fetching latest build environment...
Docker image digest: sha256:008ba7f4223f1e26c11df9575283491b620074fa96da6961e0dcde47fb757014
====>> Spin up environment
Build-agent version  ()
System information:
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: btrfs
 Cgroup Driver: systemd
 Cgroup Version: 2
 Kernel Version: 6.11.5-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64

Starting container cimg/go:1.20
Warning: No authentication provided, using CircleCI credentials for pulls from Docker Hub.
  image is cached as cimg/go:1.20, but refreshing...
1.20: Pulling from cimg/go
Digest: sha256:bd1abc34d5deb0c8f55e9f9c8071210e3a5ba9ce874f48a61a390175c2be0da6
Status: Image is up to date for cimg/go:1.20
cimg/go:1.20:
  using image cimg/go@sha256:bd1abc34d5deb0c8f55e9f9c8071210e3a5ba9ce874f48a61a390175c2be0da6
  pull stats: Image was already available so the image was not pulled
  time to create container: 117ms
Creating Docker containers in parallel 
Time to upload agent and config: 162.595656ms
Time to start containers: 457.684773ms
====>> Preparing environment variables
Using build environment variables:
  BASH_ENV=/tmp/.bash_env-localbuild-1730205231
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=
  CIRCLE_BUILD_NUM=
  CIRCLE_JOB=build
  CIRCLE_NODE_INDEX=0
  CIRCLE_NODE_TOTAL=1
  CIRCLE_REPOSITORY_URL=
  CIRCLE_SHA1=
  CIRCLE_SHELL_ENV=/tmp/.bash_env-localbuild-1730205231
  CIRCLE_WORKING_DIRECTORY=~/project


The redacted variables listed above will be masked in run step output.====>> Checkout code
Making checkout directory "/home/circleci/project"
Copying files from "/tmp/_circleci_local_build_repo" to "/home/circleci/project"
====>> go mod download
  #!/bin/bash -eo pipefail
go mod download
====>> make
  #!/bin/bash -eo pipefail
make
>> checking code style
>> vetting code
GO111MODULE= go vet  ./...
>> building ping
GO111MODULE= go build  ./cmd/ping
>> running all tests
GO111MODULE= go test -race -cover  ./...
?       github.com/prometheus-community/pro-bing/cmd/ping       [no test files]
ok      github.com/prometheus-community/pro-bing        7.105s  coverage: 67.9% of statements
Success!
```

2024-10-29 13:16 UTC, MatthieuCoder commented
Seems like using another interface did not fix the issue regarding permissions,
Specifying an interface might be unsupported in CircleCI ?

2024-10-29 14:07 UTC, SuperQ commented
We can try switching from Docker to Machine mode for CI.

2024-10-29 14:34 UTC, MatthieuCoder commented
I would like that.

2024-10-29 16:09 UTC, MatthieuCoder commented
Do I need to pull the changes on `main` for them to apply here ?

2024-10-29 16:14 UTC, MatthieuCoder commented
Permission denied still, I'll look into it tomorrow

2024-10-29 16:55 UTC, MatthieuCoder commented
As I thought, Using the machine executor does make the tests pass,
Subsequently the change from docker to machine should be in another PR, since @SuperQ's PR does not (#124) does not change the execution to the machine type

2024-10-29 17:28 UTC, SuperQ commented
Yea, the only problem with the machine image is it doesn't directly control the Go version.

2024-10-29 17:33 UTC, MatthieuCoder commented
> Yea, the only problem with the machine image is it doesn't directly control the Go version.

Indeed, I read online that this could be solved by running docker in the machine executor, this might require more configuration.

2024-10-29 17:40 UTC, MatthieuCoder commented
hold on I have a last thing to change

2024-10-29 17:48 UTC, MatthieuCoder commented
now ready!

2024-10-30 10:26 UTC, Hipska commented on ping.go
> +	Interface string
I would also pick `InterfaceName`.

2024-10-30 10:32 UTC, Hipska requested changes

2024-10-30 10:32 UTC, Hipska commented on ping.go
> +	InterfaceDevice string
Please use `InterfaceName`, it will make more sense with the `net.InterfaceByName` call 😉

2024-10-30 11:14 UTC, Hipska approved these changes

2024-10-31 10:06 UTC, SuperQ approved these changes
Thanks. We can fix the Go version matrix later. For now we can live with the version provide in the machine image.

2024-10-31 10:12 UTC, merged

2024-11-30 14:19 UTC, dswarbrick commented
Tests are failing locally for me, on Ubuntu 24.10, running the test as root.
```
--- FAIL: TestSetInterfaceName (0.00s)
    ping_test.go:490: Expected No Error but got socket: permission denied, Stack:
        goroutine 259 [running]:
        runtime/debug.Stack()
                /usr/lib/go-1.23/src/runtime/debug/stack.go:26 +0x5e
        github.com/prometheus-community/pro-bing.AssertNoError(0xc0003844e0, {0x871880, 0xc000098260})
                /home/daniel/Work/Debian/golang-github-prometheus-community-pro-bing/ping_test.go:528 +0x37
        github.com/prometheus-community/pro-bing.TestSetInterfaceName(0xc0003844e0)
                /home/daniel/Work/Debian/golang-github-prometheus-community-pro-bing/ping_test.go:490 +0x95
        testing.tRunner(0xc0003844e0, 0x80d9a0)
                /usr/lib/go-1.23/src/testing/testing.go:1690 +0xf4
        created by testing.(*T).Run in goroutine 1
                /usr/lib/go-1.23/src/testing/testing.go:1743 +0x390
```