Add support for setting SO_MARK socket option on outgoing ICMP packets
prometheus-community/pro-bing pull request #36
Opened 2023-05-18 20:31 UTC by floatingstatic

The standard ping utility in linux has a flag that can be used to set a mark on outgoing packets which is used in tandem with linux policy routing.

```
-m mark
           use mark to tag the packets going out. This is useful for variety of reasons within the kernel such as
           using policy routing to select specific outbound processing.
```

Setting a mark can be achieved in linux by setting the `SO_MARK` socket option:

```
       SO_MARK (since Linux 2.6.25)
              Set the mark for each packet sent through this socket
              (similar to the netfilter MARK target but socket-based).
              Changing the mark can be used for mark-based routing
              without netfilter or for packet filtering.  Setting this
              option requires the CAP_NET_ADMIN capability.
```

This PR attempts to adds support for this feature. Given a socket has to first exist before we can set the mark we add a `SetMark()` and `Mark()` options to set and read the intended mark to be set once the icmp conn exists. In addition to this we add a `SetMark()` method to the packetconn interface to actually set the socket option after the conn is created. This PR only attempts to set this option under linux. Other environments (windows, etc.) will throw an error if attempting to set a mark on the socket. I'm not sure if this is supported outside of linux or not.

2023-05-19 14:11 UTC, SuperQ requested changes
Thanks, a few minor issues.

2023-05-19 14:11 UTC, SuperQ commented on README.md
> +This library also supports setting the `SO_MARK` socket option which is equivalent to the `-m mark`
```suggestion
This library supports setting the `SO_MARK` socket option which is equivalent to the `-m mark`
```

2023-05-19 14:11 UTC, SuperQ commented on utils_windows.go
> +	return errors.New("setting SO_MARK socket option is not supported on this platform")
We want to make this new error a package var like this:

```
var ErrMarkNotSupported = errors.New("setting SO_MARK socket option is not supported on this platform")
```

This way it can be used with `errors.Is()`.

2023-05-19 14:11 UTC, SuperQ commented on ping.go
> +	// Mark is a mark (fwmark) set on outgoing icmp packets
```suggestion
	// mark is as SO_MARK (fwmark) set on outgoing icmp packets
```

2023-05-19 14:37 UTC, floatingstatic commented on utils_windows.go
> +	return errors.New("setting SO_MARK socket option is not supported on this platform")
Cool, I'll update this.

2023-05-19 14:44 UTC, floatingstatic commented on ping.go
> +	// Mark is a mark (fwmark) set on outgoing icmp packets
Addressed in https://github.com/prometheus-community/pro-bing/pull/36/commits/f76c67e85dca9e16e72c31a08a753c6def6fb7d6

2023-05-19 14:44 UTC, floatingstatic commented on utils_windows.go
> +	return errors.New("setting SO_MARK socket option is not supported on this platform")
https://github.com/prometheus-community/pro-bing/pull/36/commits/f76c67e85dca9e16e72c31a08a753c6def6fb7d6

2023-05-19 14:54 UTC, SuperQ commented
This needs a DCO sign-off. You can use `git commit -s --amend` to add it.

2023-05-20 05:22 UTC, SuperQ approved these changes
Thanks!

2023-05-20 05:23 UTC, merged